<?xml version="1.0" encoding="utf-8"?><Database Name="ProfilerDB" Class="ProfilerDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ProfilerDB;Persist Security Info=True;User ID=sa" SettingsObjectName="ProfilerBySSFProject.Properties.Settings" SettingsPropertyName="ProfilerDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ExcelTBL" Member="ExcelTBLs">
    <Type Name="ExcelTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="barcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="danger" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="archive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MainTBL" Member="MainTBLs">
    <Type Name="MainTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="barcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="x" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="y" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="z" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="archive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="error" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelsTBL" Member="ParcelsTBLs">
    <Type Name="ParcelsTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="barcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="width" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="height" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="length" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="danger" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParcelTBL" Member="ParcelTBLs">
    <Type Name="ParcelTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="barcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="x" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="y" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="z" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="weight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="error" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SetupTBL" Member="SetupTBLs">
    <Type Name="SetupTBL">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="version" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="path" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ip_delta" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="camFARLEFT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="camLEFT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="camBACK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="camTOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="camFRONT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="camTOP2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="camRIGHT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="camFARRIGHT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sheets" Member="sheets">
    <Type Name="sheet">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Barcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>